export default [
  {
    id: "1",
    title: "First Data result",
    description: "*Author*: Brian Johnson\n *Source*: [UCI] (https://archive.ics.uci.edu/ml/datasets/Wilt)\n *Please cite*: Johnson, B., Tateishi, R., Hoan, N., 2013. A hybrid pansharpening approach and multiscale object-based image analysis for mapping diseased pine and oak trees. International Journal of Remote Sensing, 34 (20), 6969-6982.\n \n __Changes w.r.t. version 1: renamed variables such that they match description.__\n \n \n ###Dataset:\n Wilt Data Set\n \n ###Abstract:\n High-resolution Remote Sensing data set (Quickbird). Small number of training samples of diseased trees, large number for other land cover. Testing data set from stratified random sample of image.\n \n ###Source:\n \n Brian Johnson;\n Institute for Global Environmental Strategies;\n 2108-11 Kamiyamaguchi, Hayama, Kanagawa,240-0115 Japan;\n Email: Johnson '@' iges.or.jp\n \n \n ###Data Set Information:\n \n This data set contains some training and testing data from a remote sensing study by Johnson et al. (2013) that involved detecting diseased trees in Quickbird imagery. There are few training samples for the 'diseased trees' class (74) and many for 'other land cover' class (4265).\n \n The data set consists of image segments, generated by segmenting the pansharpened image. The segments contain spectral information from the Quickbird multispectral image bands and texture information from the panchromatic (Pan) image band. The testing data set is for the row with \\xe2\\u20ac\\u0153Segmentation scale 15\\xe2\\u20ac\\x9d segments and \\xe2\\u20ac\\u0153original multi-spectral image\\xe2\\u20ac\\x9d Spectral information in Table 2 of the reference (i.e. row 5). Please see the reference below for more information on the data set, and please cite the reference if you use this data set. Enjoy!\n \n ###Attribute Information:\n \n class: 'w' (diseased trees), 'n' (all other land cover)\n GLCM_Pan: GLCM mean texture (Pan band)\n Mean_G: Mean green value\n Mean_R: Mean red value\n Mean_NIR: Mean NIR value\n SD_Pan: Standard deviation (Pan band)\n \n \n ###Relevant Papers:\n \n Johnson, B., Tateishi, R., Hoan, N., 2013. A hybrid pansharpening approach and multiscale object-based image analysis for mapping diseased pine and oak trees. International Journal of Remote Sensing, 34 (20), 6969-6982.",
    price: 50,
    fileType: "pdf",
    fileSize: "20 MB"
  },
  {
    id: "2",
    title: "Second Data result",
    description: "This is a second data result composed of many other results.",
    price: 0,
    fileType: "csv",
    fileSize: "4.3 MB"
  },
  {
    id: "3",
    title: "Third Data result",
    description: "This is a third data result composed of many other results.",
    price: 500,
    fileType: "pdf",
    fileSize: "2 MB"
  },
  {
    id: "4",
    title: "Fourth Data result",
    description: "This is a forth data result composed of many other results.",
    price: 12.5,
    fileType: "txt",
    fileSize: "128 KB"
  },
  {
    id: "5",
    title: "Fifth Data result",
    description: "This is a fifth data result composed of many other results.",
    price: 210,
    fileType: "zip",
    fileSize: "2 GB"
  },
  {
    id: "6",
    title: "First Data result",
    description: "This is a first data result composed of many other results.",
    price: 50,
    fileType: "pdf",
    fileSize: "20 MB"
  },
  {
    id: "7",
    title: "Second Data result",
    description: "This is a second data result composed of many other results.",
    price: 0,
    fileType: "csv",
    fileSize: "4.3 MB"
  },
  {
    id: "8",
    title: "Third Data result",
    description: "This is a third data result composed of many other results.",
    price: 500,
    fileType: "pdf",
    fileSize: "2 MB"
  },
  {
    id: "9",
    title: "Fourth Data result",
    description: "This is a forth data result composed of many other results.",
    price: 12.5,
    fileType: "txt",
    fileSize: "128 KB"
  },
  {
    id: "10",
    title: "Fifth Data result",
    description: "This is a fifth data result composed of many other results.",
    price: 210,
    fileType: "zip",
    fileSize: "2 GB"
  },
  {
    id: "11",
    title: "First Data result",
    description: "This is a first data result composed of many other results.",
    price: 50,
    fileType: "pdf",
    fileSize: "20 MB"
  },
  {
    id: "12",
    title: "Second Data result",
    description: "This is a second data result composed of many other results.",
    price: 0,
    fileType: "csv",
    fileSize: "4.3 MB"
  },
  {
    id: "13",
    title: "Third Data result",
    description: "This is a third data result composed of many other results.",
    price: 500,
    fileType: "pdf",
    fileSize: "2 MB"
  },
  {
    id: "14",
    title: "Fourth Data result",
    description: "This is a forth data result composed of many other results.",
    price: 12.5,
    fileType: "txt",
    fileSize: "128 KB"
  },
  {
    id: "15",
    title: "Fifth Data result",
    description: "This is a fifth data result composed of many other results.",
    price: 210,
    fileType: "zip",
    fileSize: "2 GB"
  }
];
